<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
  <ProjectReference Include="..\TmsApi.Domain\TmsApi.Domain.csproj" />
  <ProjectReference Include="..\TmsApi.Application\TmsApi.Application.csproj" />
</ItemGroup>

  <!-- <ItemGroup>
    <Compile Include="Persistence\**\*.cs" />
    <Compile Include="..\Data\DataSeeder.cs" Link="Persistence\DataSeeder.cs" />
    <Compile Remove="Services\**\*.cs" />
  </ItemGroup> -->

  <ItemGroup>
    <Compile Include="Persistence\**\*.cs" />
    <Compile Include="Services\**\*.cs" />
    <Compile Include="Caching\**\*.cs" />
    <Compile Include="..\Data\DataSeeder.cs" Link="Persistence\DataSeeder.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

</Project>
