<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.8.0" />
    <!-- <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" /> -->
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TmsApi.Application\TmsApi.Application.csproj" />
    <ProjectReference Include="..\TmsApi.Infrastructure\TmsApi.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Filters\**\*.cs" Link="Filters\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\Middleware\**\*.cs" Link="Middleware\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\RequestLoggingMiddleware.cs" Link="RequestLoggingMiddleware.cs" />
    <Compile Include="..\WeatherForecast.cs" Link="WeatherForecast.cs" />
  </ItemGroup>

</Project>
